#!/usr/bin/env python3
"""Generate sinlut.h"""

import math

header = """/*!
    @file
    @brief Lookup table for sin.

    This file was generated by `sinlut.py`.
*/

#ifndef SINLUT_H
#define SINLUT_H

const int8_t PROGMEM sin_LUT[] = {
"""

footer = """};

#endif  // SINLUT_H
"""


if __name__ == '__main__':
    with open('sinlut.h', 'w') as f:
        f.write(header)
        for i in range(0, 256):
            value = int(math.sin(2*math.pi / 256 * i) * 127)
            f.write(f'    {value},  // {i}\n')
        f.write(footer)
